[package]
name = "mc2"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
derive_more = { version = "2.1.1", features = ["error", "display"] }
# docker = "0.0.41"
